name: test-check
on:
  push:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      api-finance-tracker: ${{ steps.filter.outputs.api-finance-tracker }}
      web-financial-planner: ${{ steps.filter.outputs.web-financial-planner }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            api-finance-tracker:
              - 'api-finance-tracker/**'
            web-financial-planner:
              - 'web-financial-planner/**'

  build-api-finance-tracker:
    needs: changes
    if: needs.changes.outputs.api-finance-tracker == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api-finance-tracker
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "24.13.1"
          cache: "npm"
          cache-dependency-path: api-finance-tracker/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run vitest tests
        run: vitest run

  build-web-financial-planner:
    needs: changes
    if: needs.changes.outputs.web-financial-planner == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web-financial-planner
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "24.13.1"
          cache: "npm"
          cache-dependency-path: web-financial-planner/package-lock.json

      - name: Create .env
        run: |
          cat << EOF > .env
          EMPTY=0
          EOF

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: vitest run
